import type { Category, Product, Supermarket } from "@/types/database"

const catId = {
  hortifruti: "cat-hortifruti",
  carnes: "cat-carnes",
  bebidas: "cat-bebidas",
  laticinios: "cat-laticinios",
  limpeza: "cat-limpeza",
  higiene: "cat-higiene",
  congelados: "cat-congelados",
  padaria: "cat-padaria",
  outros: "cat-outros",
}

export const DEFAULT_CATEGORIES: Category[] = [
  { id: catId.hortifruti, name: "Hortifruti", icon: "🥬", sort_order: 1, created_at: "" },
  { id: catId.carnes, name: "Carnes", icon: "🥩", sort_order: 2, created_at: "" },
  { id: catId.bebidas, name: "Bebidas", icon: "🥤", sort_order: 3, created_at: "" },
  { id: catId.laticinios, name: "Laticínios", icon: "🧀", sort_order: 4, created_at: "" },
  { id: catId.limpeza, name: "Limpeza", icon: "🧹", sort_order: 5, created_at: "" },
  { id: catId.higiene, name: "Higiene", icon: "🧴", sort_order: 6, created_at: "" },
  { id: catId.congelados, name: "Congelados", icon: "🧊", sort_order: 7, created_at: "" },
  { id: catId.padaria, name: "Padaria", icon: "🍞", sort_order: 8, created_at: "" },
  { id: catId.outros, name: "Outros", icon: "📦", sort_order: 9, created_at: "" },
]

function p(id: string, name: string, icon: string, categoryId: string): Product {
  return { id, name, icon, photo_url: null, category_id: categoryId, created_at: "" }
}

export const DEFAULT_PRODUCTS: Product[] = [
  // Hortifruti
  p("p-banana", "Banana", "🍌", catId.hortifruti),
  p("p-maca", "Maçã", "🍎", catId.hortifruti),
  p("p-laranja", "Laranja", "🍊", catId.hortifruti),
  p("p-tomate", "Tomate", "🍅", catId.hortifruti),
  p("p-cebola", "Cebola", "🧅", catId.hortifruti),
  p("p-alho", "Alho", "🧄", catId.hortifruti),
  p("p-batata", "Batata", "🥔", catId.hortifruti),
  p("p-cenoura", "Cenoura", "🥕", catId.hortifruti),
  p("p-alface", "Alface", "🥬", catId.hortifruti),
  p("p-limao", "Limão", "🍋", catId.hortifruti),
  p("p-manga", "Manga", "🥭", catId.hortifruti),
  p("p-melancia", "Melancia", "🍉", catId.hortifruti),
  p("p-uva", "Uva", "🍇", catId.hortifruti),
  p("p-morango", "Morango", "🍓", catId.hortifruti),
  p("p-abacaxi", "Abacaxi", "🍍", catId.hortifruti),
  p("p-pepino", "Pepino", "🥒", catId.hortifruti),
  p("p-pimentao", "Pimentão", "🫑", catId.hortifruti),
  p("p-milho", "Milho", "🌽", catId.hortifruti),
  p("p-brocolis", "Brócolis", "🥦", catId.hortifruti),
  p("p-couve", "Couve", "🥗", catId.hortifruti),

  // Carnes
  p("p-frango-peito", "Frango (peito)", "🍗", catId.carnes),
  p("p-frango-coxa", "Frango (coxa)", "🍗", catId.carnes),
  p("p-carne-moida", "Carne moída", "🥩", catId.carnes),
  p("p-bisteca", "Bisteca suína", "🥩", catId.carnes),
  p("p-costela", "Costela", "🥩", catId.carnes),
  p("p-linguica", "Linguiça", "🌭", catId.carnes),
  p("p-ovos", "Ovos", "🥚", catId.carnes),
  p("p-peixe", "Peixe (filé)", "🐟", catId.carnes),
  p("p-bacon", "Bacon", "🥓", catId.carnes),
  p("p-presunto", "Presunto", "🥩", catId.carnes),

  // Bebidas
  p("p-agua", "Água mineral", "💧", catId.bebidas),
  p("p-refrigerante", "Refrigerante", "🥤", catId.bebidas),
  p("p-suco-laranja", "Suco de laranja", "🧃", catId.bebidas),
  p("p-cafe", "Café em pó", "☕", catId.bebidas),
  p("p-cha", "Chá", "🍵", catId.bebidas),
  p("p-achocolatado", "Achocolatado", "🍫", catId.bebidas),
  p("p-cerveja", "Cerveja", "🍺", catId.bebidas),
  p("p-vinho", "Vinho", "🍷", catId.bebidas),

  // Laticínios
  p("p-leite-integral", "Leite integral", "🥛", catId.laticinios),
  p("p-leite-desnatado", "Leite desnatado", "🥛", catId.laticinios),
  p("p-queijo-mucarela", "Queijo muçarela", "🧀", catId.laticinios),
  p("p-queijo-prato", "Queijo prato", "🧀", catId.laticinios),
  p("p-iogurte", "Iogurte natural", "🫙", catId.laticinios),
  p("p-manteiga", "Manteiga", "🧈", catId.laticinios),
  p("p-requeijao", "Requeijão", "🫙", catId.laticinios),
  p("p-creme-leite", "Creme de leite", "🥛", catId.laticinios),
  p("p-leite-condensado", "Leite condensado", "🥫", catId.laticinios),

  // Limpeza
  p("p-detergente", "Detergente", "🧴", catId.limpeza),
  p("p-sabao-po", "Sabão em pó", "🫧", catId.limpeza),
  p("p-amaciante", "Amaciante", "🌸", catId.limpeza),
  p("p-agua-sanitaria", "Água sanitária", "🧪", catId.limpeza),
  p("p-desinfetante", "Desinfetante", "🧹", catId.limpeza),
  p("p-esponja", "Esponja", "🧽", catId.limpeza),
  p("p-saco-lixo", "Saco de lixo", "🗑️", catId.limpeza),
  p("p-papel-toalha", "Papel toalha", "🧻", catId.limpeza),
  p("p-lustra-moveis", "Lustra-móveis", "✨", catId.limpeza),

  // Higiene
  p("p-papel-higienico", "Papel higiênico", "🧻", catId.higiene),
  p("p-sabonete", "Sabonete", "🧼", catId.higiene),
  p("p-shampoo", "Shampoo", "🧴", catId.higiene),
  p("p-condicionador", "Condicionador", "🧴", catId.higiene),
  p("p-creme-dental", "Creme dental", "🪥", catId.higiene),
  p("p-desodorante", "Desodorante", "🧴", catId.higiene),
  p("p-fio-dental", "Fio dental", "🦷", catId.higiene),
  p("p-cotonete", "Cotonete", "🏥", catId.higiene),

  // Congelados
  p("p-pizza", "Pizza congelada", "🍕", catId.congelados),
  p("p-lasanha", "Lasanha congelada", "🍝", catId.congelados),
  p("p-hamburguer", "Hambúrguer", "🍔", catId.congelados),
  p("p-sorvete", "Sorvete", "🍦", catId.congelados),
  p("p-nuggets", "Nuggets", "🍗", catId.congelados),
  p("p-acai", "Açaí", "🫐", catId.congelados),

  // Padaria
  p("p-pao-frances", "Pão francês", "🥖", catId.padaria),
  p("p-pao-forma", "Pão de forma", "🍞", catId.padaria),
  p("p-bolo", "Bolo pronto", "🍰", catId.padaria),
  p("p-biscoito-cc", "Biscoito cream cracker", "🍘", catId.padaria),
  p("p-biscoito-rech", "Biscoito recheado", "🍪", catId.padaria),
  p("p-rosquinha", "Rosquinha", "🍩", catId.padaria),

  // Outros (Mercearia)
  p("p-arroz", "Arroz", "🍚", catId.outros),
  p("p-feijao", "Feijão", "🫘", catId.outros),
  p("p-macarrao", "Macarrão", "🍝", catId.outros),
  p("p-oleo", "Óleo de soja", "🫗", catId.outros),
  p("p-azeite", "Azeite", "🫒", catId.outros),
  p("p-acucar", "Açúcar", "🍬", catId.outros),
  p("p-sal", "Sal", "🧂", catId.outros),
  p("p-farinha", "Farinha de trigo", "🌾", catId.outros),
  p("p-molho-tomate", "Molho de tomate", "🥫", catId.outros),
  p("p-maionese", "Maionese", "🫙", catId.outros),
  p("p-ketchup", "Ketchup", "🥫", catId.outros),
  p("p-vinagre", "Vinagre", "🫗", catId.outros),
  p("p-margarina", "Margarina", "🧈", catId.outros),
  p("p-extrato-tomate", "Extrato de tomate", "🥫", catId.outros),
  p("p-tempero", "Tempero pronto", "🌿", catId.outros),
  p("p-fuba", "Fubá", "🌽", catId.outros),
  p("p-aveia", "Aveia", "🥣", catId.outros),
]

export const DEFAULT_SUPERMARKETS: Supermarket[] = [
  // Grandes redes com forte presença em MG
  {
    id: "sm-epa",
    name: "EPA Supermercados",
    city: "Belo Horizonte",
    notes: "Rede mineira com mais de 100 lojas em MG",
    color: "#0066CC",
    initials: "EPA",
    created_at: "",
  },
  {
    id: "sm-supernosso",
    name: "Super Nosso",
    city: "Belo Horizonte",
    notes: "Rede premium com lojas na Grande BH",
    color: "#E31937",
    initials: "SN",
    created_at: "",
  },
  {
    id: "sm-verdemar",
    name: "Verdemar",
    city: "Belo Horizonte",
    notes: "Supermercado premium, produtos selecionados",
    color: "#228B22",
    initials: "VM",
    created_at: "",
  },
  {
    id: "sm-apoio",
    name: "Apoio Mineiro",
    city: "Belo Horizonte",
    notes: "Rede atacarejo do grupo DMA",
    color: "#FF6600",
    initials: "AM",
    created_at: "",
  },
  {
    id: "sm-bretas",
    name: "Bretas",
    city: "Uberlândia",
    notes: "Rede do grupo CENCOSUD, presente em todo MG",
    color: "#CC0000",
    initials: "BR",
    created_at: "",
  },
  {
    id: "sm-bh",
    name: "Supermercados BH",
    city: "Belo Horizonte",
    notes: "Uma das maiores redes de MG",
    color: "#003399",
    initials: "BH",
    created_at: "",
  },
  {
    id: "sm-mart",
    name: "Mart Minas",
    city: "Belo Horizonte",
    notes: "Atacarejo do grupo ABC, presente em MG",
    color: "#FF0000",
    initials: "MM",
    created_at: "",
  },
  {
    id: "sm-abc",
    name: "Supermercados ABC",
    city: "Belo Horizonte",
    notes: "Rede regional mineira",
    color: "#0099CC",
    initials: "ABC",
    created_at: "",
  },
  {
    id: "sm-bahamas",
    name: "Bahamas Supermercados",
    city: "Juiz de Fora",
    notes: "Forte presença na Zona da Mata e Sul de MG",
    color: "#FFD700",
    initials: "BA",
    created_at: "",
  },
  {
    id: "sm-villefort",
    name: "Villefort Atacadista",
    city: "Belo Horizonte",
    notes: "Atacarejo com lojas na Grande BH",
    color: "#8B0000",
    initials: "VF",
    created_at: "",
  },
  {
    id: "sm-carrefour",
    name: "Carrefour",
    city: "Belo Horizonte",
    notes: "Rede internacional, várias lojas em MG",
    color: "#004E9A",
    initials: "CR",
    created_at: "",
  },
  {
    id: "sm-atacadao",
    name: "Atacadão",
    city: "Belo Horizonte",
    notes: "Atacarejo do grupo Carrefour",
    color: "#E30613",
    initials: "AT",
    created_at: "",
  },
  {
    id: "sm-assai",
    name: "Assaí Atacadista",
    city: "Belo Horizonte",
    notes: "Atacarejo com preços de atacado",
    color: "#FFC107",
    initials: "AS",
    created_at: "",
  },
  {
    id: "sm-rede-minas",
    name: "Rede Minas",
    city: "Contagem",
    notes: "Rede regional do interior de MG",
    color: "#2E7D32",
    initials: "RM",
    created_at: "",
  },
  {
    id: "sm-rex",
    name: "Supermercados Rex",
    city: "Uberlândia",
    notes: "Rede tradicional do Triângulo Mineiro",
    color: "#9C27B0",
    initials: "RX",
    created_at: "",
  },
  {
    id: "sm-dma",
    name: "DMA Distribuidora",
    city: "Belo Horizonte",
    notes: "Distribuidora e varejo do grupo DMA",
    color: "#1565C0",
    initials: "DMA",
    created_at: "",
  },
  {
    id: "sm-nacional",
    name: "Supermercado Nacional",
    city: "Belo Horizonte",
    notes: "Rede com várias lojas em BH e região",
    color: "#00695C",
    initials: "NA",
    created_at: "",
  },
]
